map_height: 7
map_width: 7
n_actions: 8
reward_states: [[6,3]]
terminal_states: [[6,3]]
unsafe_states: [[[1,3]], [[3,4], [3,2], [3,3]], [[5,1], [5,2], [5,3], [5,4], [5,5]]]
start_states: [[0,3]]
