task: 'ME-PPO-Lag-HC'
group: 'PPO-Lag'
device: 'cuda'
verbose: 2
env:
  config_path: null
  train_env_id : 'HCWithPos-v0'
  eval_env_id: 'HCWithPos-v0'  # 'HCWithPosTest-v0'
  constraint_id: 1  # the id of constraint, 0: the first constraint, 1: the second constraint, null: dynamic constraints
  save_dir: '../save_model'
  cost_info_str: 'cost'
  use_cost: True
  reward_gamma: 0.99
  cost_gamma: 0.99  # no cost
  dont_normalize_obs: False
  dont_normalize_reward: False
  dont_normalize_cost: False  # cost
  record_info_names: ["xpos"]

running:
  n_iters: 30
  n_eval_episodes: 10
  save_every: 5
  latent_dim: 2
  render: False  

PPO:
  policy_name: 'TwoCriticsMlpPolicy'
  learning_rate: 0.0003
  n_steps: 2048
  n_epochs: 10
  reward_gamma: 0.99
  reward_gae_lambda: 0.95
  cost_gamma: 0.99
  cost_gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  reward_vf_coef: 0.5
  cost_vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1
  target_kl: 0.01
  shared_layers: null
  policy_layers: [64, 64]
  reward_vf_layers: [64, 64]
  cost_vf_layers: [64, 64]
  batch_size: 64
  eval_every: 2048
  use_curiosity_driven_exploration: False
  warmup_timesteps: False
  reset_policy: False
  forward_timesteps: 200000
  clip_range_reward_vf: null
  clip_range_cost_vf: null
  penalty_initial_value: 1
  penalty_learning_rate: 0.1
  budget: 0
  proportional_control_coeff: 10
  integral_control_coeff: 0.0001
  derivative_control_coeff: 0
  pid_delay: 1
  proportional_cost_ema_alpha: 0.5
  derivative_cost_ema_alpha: 0.5
