map_height: 7
map_width: 7
n_actions: 8
reward_states: [[0, 6]]
terminal_states: [[0, 6]]
unsafe_states: [[[0,3]], [[0,3], [1,3]], [[0,3], [1,3], [2,3], [3,3]],[[0,3], [1,3], [2,3], [3,3], [4,3]]]
start_states: [[0,0]]